### ISSUE TITLE
Leaderboard - Show scores after game is finished and until new game is started

### ISSUE THREAD

**Issue by EricSSartorius** [EricSSartorius/Judging-System#23]
Currently, the Leaderboard can only be seen when inGame is set to 'true.' This makes it so after the event has ended the Leaderboard can no longer be seen. Need to make a fix so that the Leaderboard can be seen not only during the event but until a different event is started.

**Comment by felicedeNigris** [comment]
Hey Eric,

So with this task. I was wondering If I can take this one on ?

So basically you want to view leaderboards for 'ALL' games. Meaning 'current' and 'past' games ? 
I'm trying to better understand it.

**Comment by EricSSartorius** [comment]
Hey @felicedeNigris ,
Sorry, my wording was a bit bad. The leaderboard should only be showing for one event at a time. Right now if the event is running then the leaderboard will show. But I want the leaderboard to show up until a different event has started. I sent a slack message with a bit more detail on how to make it work.
