### ISSUE TITLE
Update Login options

### ISSUE THREAD

**Issue by EricSSartorius** [EricSSartorius/Judging-System#46]
The following needs to be done to update the login/register process
- [x] Ask for user's first name when registering
- [x] Have the name shown next to the word 'Logout' when the user is logged in
- [x] Have the email registered with tie to a real email account. This involves sending a confirmation email to the registered email
- [x] Get the password reset screen up and working once users are tied to real email accounts

**Comment by felicedeNigris** [comment]
Hey Eric, I want to give this a shot. Let me know if it's up for grabs

**Comment by EricSSartorius** [comment]
Yea sure go for it.

**Comment by felicedeNigris** [comment]
F**ck Yeah!! Lost Password .. and reset password email working!!!

**Comment by EricSSartorius** [comment]
Great work!
